### ISSUE TITLE
Snap memories

### ISSUE THREAD

**Issue by tgreen229922** [evanugarte/snapchat-memories-downloader#27]

**Comment by evanugarte** [comment]
true

**Comment by danknessdra** [comment]
true

**Comment by marcobmr** [comment]
Why did you shut down ur Website, the Snapchat Download isn't working right... They don't ad the timestamp.

**Comment by evanugarte** [comment]
Snapchat now lets you download memories directly from the data request, so the website is no longer needed. For more information on how to do this, see

https://help.snapchat.com/hc/en-us/articles/7012305371156-How-do-I-download-my-data-from-Snapchat-
